[profile.default]
# The source directory
src = 'src'
# The test directory
test = 'test'
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ['lib']
# Whether to cache builds or not
cache = true
# Whether to ignore the cache
force = false
# The verbosity of tests
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc_version = '0.8.18'
optimizer = true
optimizer_runs = 1000000
via_ir = true
# optimizer_steps = ''

fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
anvil = "http://127.0.0.1:8545"

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }


